name: build-site

on:
  schedule:
    - cron: "*/30 * * * *"   # cada 30 min
  workflow_dispatch: {}      # ejecutar manual

concurrency:
  group: build-site
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Generate dashboard (docs/index.html)
        run: |
          set -e
          python generate_dashboard_dinaticket.py
          test -f docs/index.html
          echo "UTC now: $(date -u)"
          echo "Madrid now: $(TZ=Europe/Madrid date '+%Y-%m-%d %H:%M:%S')"

      - name: Commit & push if docs changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f docs/index.html
          if git diff --cached --quiet; then
            echo "No changes, nothing to commit."
          else
            git commit -m "Auto-update dashboard ($(TZ=Europe/Madrid date '+%Y-%m-%d %H:%M'))"
            git push origin main
          fi
