name: build-site

on:
  schedule:
    # Run every 30 minutes (at :00 and :30)
    - cron: "0,30 * * * *"
  workflow_dispatch:
    inputs:
      force:
        description: "Force run (ignore the :00/:30 gate)"
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Check Madrid minute gate
        id: gate
        run: |
          MM=$(TZ=Europe/Madrid date +%M)
          echo "mm=$MM" >> $GITHUB_OUTPUT
          echo "⏱️ Minuto Madrid = $MM"

      - name: Stop unless it's :00 or :30 (or forced)
        if: ${{ steps.gate.outputs.mm != '00' && steps.gate.outputs.mm != '30' && github.event.inputs.force != 'true' }}
        run: |
          echo "⏹️ Not time to run (minute != 00 or 30 and not forced)"
          exit 0

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Generate dashboard
        run: python3 generate_dashboard_dinaticket.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.html || true
          git commit -m "Auto-update dashboard ($(TZ=Europe/Madrid date))" || echo "No changes"
          git push origin main || echo "Nothing to push"
